// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TSAArchives.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TSAArchives.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace TSA {

namespace {

const ::google::protobuf::Descriptor* DocumentArchive_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DocumentArchive_reflection_ = NULL;
const ::google::protobuf::Descriptor* FunctionBrowserStateArchive_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FunctionBrowserStateArchive_reflection_ = NULL;
const ::google::protobuf::Descriptor* TestDocumentArchive_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TestDocumentArchive_reflection_ = NULL;
const ::google::protobuf::Descriptor* PropagatePresetCommandArchive_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PropagatePresetCommandArchive_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_TSAArchives_2eproto() {
  protobuf_AddDesc_TSAArchives_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TSAArchives.proto");
  GOOGLE_CHECK(file != NULL);
  DocumentArchive_descriptor_ = file->message_type(0);
  static const int DocumentArchive_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, super_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, text_preset_display_items_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, creation_language_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, calculation_engine_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, view_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, function_browser_state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, tables_custom_format_list_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, needs_movie_compatibility_upgrade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, template_identifier_),
  };
  DocumentArchive_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DocumentArchive_descriptor_,
      DocumentArchive::default_instance_,
      DocumentArchive_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DocumentArchive, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DocumentArchive));
  FunctionBrowserStateArchive_descriptor_ = file->message_type(1);
  static const int FunctionBrowserStateArchive_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionBrowserStateArchive, recent_functions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionBrowserStateArchive, back_functions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionBrowserStateArchive, forward_functions_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionBrowserStateArchive, current_function_),
  };
  FunctionBrowserStateArchive_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      FunctionBrowserStateArchive_descriptor_,
      FunctionBrowserStateArchive::default_instance_,
      FunctionBrowserStateArchive_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionBrowserStateArchive, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionBrowserStateArchive, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(FunctionBrowserStateArchive));
  TestDocumentArchive_descriptor_ = file->message_type(2);
  static const int TestDocumentArchive_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestDocumentArchive, super_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestDocumentArchive, value_),
  };
  TestDocumentArchive_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TestDocumentArchive_descriptor_,
      TestDocumentArchive::default_instance_,
      TestDocumentArchive_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestDocumentArchive, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TestDocumentArchive, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TestDocumentArchive));
  PropagatePresetCommandArchive_descriptor_ = file->message_type(3);
  static const int PropagatePresetCommandArchive_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropagatePresetCommandArchive, super_),
  };
  PropagatePresetCommandArchive_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PropagatePresetCommandArchive_descriptor_,
      PropagatePresetCommandArchive::default_instance_,
      PropagatePresetCommandArchive_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropagatePresetCommandArchive, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PropagatePresetCommandArchive, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PropagatePresetCommandArchive));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TSAArchives_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DocumentArchive_descriptor_, &DocumentArchive::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    FunctionBrowserStateArchive_descriptor_, &FunctionBrowserStateArchive::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TestDocumentArchive_descriptor_, &TestDocumentArchive::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PropagatePresetCommandArchive_descriptor_, &PropagatePresetCommandArchive::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_TSAArchives_2eproto() {
  delete DocumentArchive::default_instance_;
  delete DocumentArchive_reflection_;
  delete FunctionBrowserStateArchive::default_instance_;
  delete FunctionBrowserStateArchive_reflection_;
  delete TestDocumentArchive::default_instance_;
  delete TestDocumentArchive_reflection_;
  delete PropagatePresetCommandArchive::default_instance_;
  delete PropagatePresetCommandArchive_reflection_;
}

void protobuf_AddDesc_TSAArchives_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::TSK::protobuf_AddDesc_TSKArchives_2eproto();
  ::TSP::protobuf_AddDesc_TSPMessages_2eproto();
  ::TSWP::protobuf_AddDesc_TSWPArchives_2eproto();
  ::TSS::protobuf_AddDesc_TSSArchives_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021TSAArchives.proto\022\003TSA\032\021TSKArchives.pr"
    "oto\032\021TSPMessages.proto\032\022TSWPArchives.pro"
    "to\032\021TSSArchives.proto\"\223\003\n\017DocumentArchiv"
    "e\022#\n\005super\030\001 \002(\0132\024.TSK.DocumentArchive\022E"
    "\n\031text_preset_display_items\030\002 \003(\0132\".TSWP"
    ".TextPresetDisplayItemArchive\022\031\n\021creatio"
    "n_language\030\003 \001(\t\022*\n\022calculation_engine\030\004"
    " \001(\0132\016.TSP.Reference\022\"\n\nview_state\030\005 \001(\013"
    "2\016.TSP.Reference\022.\n\026function_browser_sta"
    "te\030\006 \001(\0132\016.TSP.Reference\0221\n\031tables_custo"
    "m_format_list\030\007 \001(\0132\016.TSP.Reference\022)\n!n"
    "eeds_movie_compatibility_upgrade\030\010 \001(\010\022\033"
    "\n\023template_identifier\030\t \001(\t\"\204\001\n\033Function"
    "BrowserStateArchive\022\030\n\020recent_functions\030"
    "\001 \003(\r\022\026\n\016back_functions\030\002 \003(\r\022\031\n\021forward"
    "_functions\030\003 \003(\r\022\030\n\020current_function\030\004 \001"
    "(\r\"I\n\023TestDocumentArchive\022#\n\005super\030\001 \002(\013"
    "2\024.TSA.DocumentArchive\022\r\n\005value\030\002 \001(\t\"C\n"
    "\035PropagatePresetCommandArchive\022\"\n\005super\030"
    "\001 \002(\0132\023.TSK.CommandArchive", 786);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TSAArchives.proto", &protobuf_RegisterTypes);
  DocumentArchive::default_instance_ = new DocumentArchive();
  FunctionBrowserStateArchive::default_instance_ = new FunctionBrowserStateArchive();
  TestDocumentArchive::default_instance_ = new TestDocumentArchive();
  PropagatePresetCommandArchive::default_instance_ = new PropagatePresetCommandArchive();
  DocumentArchive::default_instance_->InitAsDefaultInstance();
  FunctionBrowserStateArchive::default_instance_->InitAsDefaultInstance();
  TestDocumentArchive::default_instance_->InitAsDefaultInstance();
  PropagatePresetCommandArchive::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TSAArchives_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TSAArchives_2eproto {
  StaticDescriptorInitializer_TSAArchives_2eproto() {
    protobuf_AddDesc_TSAArchives_2eproto();
  }
} static_descriptor_initializer_TSAArchives_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int DocumentArchive::kSuperFieldNumber;
const int DocumentArchive::kTextPresetDisplayItemsFieldNumber;
const int DocumentArchive::kCreationLanguageFieldNumber;
const int DocumentArchive::kCalculationEngineFieldNumber;
const int DocumentArchive::kViewStateFieldNumber;
const int DocumentArchive::kFunctionBrowserStateFieldNumber;
const int DocumentArchive::kTablesCustomFormatListFieldNumber;
const int DocumentArchive::kNeedsMovieCompatibilityUpgradeFieldNumber;
const int DocumentArchive::kTemplateIdentifierFieldNumber;
#endif  // !_MSC_VER

DocumentArchive::DocumentArchive()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DocumentArchive::InitAsDefaultInstance() {
  super_ = const_cast< ::TSK::DocumentArchive*>(&::TSK::DocumentArchive::default_instance());
  calculation_engine_ = const_cast< ::TSP::Reference*>(&::TSP::Reference::default_instance());
  view_state_ = const_cast< ::TSP::Reference*>(&::TSP::Reference::default_instance());
  function_browser_state_ = const_cast< ::TSP::Reference*>(&::TSP::Reference::default_instance());
  tables_custom_format_list_ = const_cast< ::TSP::Reference*>(&::TSP::Reference::default_instance());
}

DocumentArchive::DocumentArchive(const DocumentArchive& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DocumentArchive::SharedCtor() {
  _cached_size_ = 0;
  super_ = NULL;
  creation_language_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  calculation_engine_ = NULL;
  view_state_ = NULL;
  function_browser_state_ = NULL;
  tables_custom_format_list_ = NULL;
  needs_movie_compatibility_upgrade_ = false;
  template_identifier_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DocumentArchive::~DocumentArchive() {
  SharedDtor();
}

void DocumentArchive::SharedDtor() {
  if (creation_language_ != &::google::protobuf::internal::kEmptyString) {
    delete creation_language_;
  }
  if (template_identifier_ != &::google::protobuf::internal::kEmptyString) {
    delete template_identifier_;
  }
  if (this != default_instance_) {
    delete super_;
    delete calculation_engine_;
    delete view_state_;
    delete function_browser_state_;
    delete tables_custom_format_list_;
  }
}

void DocumentArchive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DocumentArchive::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DocumentArchive_descriptor_;
}

const DocumentArchive& DocumentArchive::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TSAArchives_2eproto();
  return *default_instance_;
}

DocumentArchive* DocumentArchive::default_instance_ = NULL;

DocumentArchive* DocumentArchive::New() const {
  return new DocumentArchive;
}

void DocumentArchive::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_super()) {
      if (super_ != NULL) super_->::TSK::DocumentArchive::Clear();
    }
    if (has_creation_language()) {
      if (creation_language_ != &::google::protobuf::internal::kEmptyString) {
        creation_language_->clear();
      }
    }
    if (has_calculation_engine()) {
      if (calculation_engine_ != NULL) calculation_engine_->::TSP::Reference::Clear();
    }
    if (has_view_state()) {
      if (view_state_ != NULL) view_state_->::TSP::Reference::Clear();
    }
    if (has_function_browser_state()) {
      if (function_browser_state_ != NULL) function_browser_state_->::TSP::Reference::Clear();
    }
    if (has_tables_custom_format_list()) {
      if (tables_custom_format_list_ != NULL) tables_custom_format_list_->::TSP::Reference::Clear();
    }
    needs_movie_compatibility_upgrade_ = false;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (has_template_identifier()) {
      if (template_identifier_ != &::google::protobuf::internal::kEmptyString) {
        template_identifier_->clear();
      }
    }
  }
  text_preset_display_items_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DocumentArchive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .TSK.DocumentArchive super = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_super()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_text_preset_display_items;
        break;
      }

      // repeated .TSWP.TextPresetDisplayItemArchive text_preset_display_items = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_text_preset_display_items:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_text_preset_display_items()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_text_preset_display_items;
        if (input->ExpectTag(26)) goto parse_creation_language;
        break;
      }

      // optional string creation_language = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_creation_language:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_creation_language()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->creation_language().data(), this->creation_language().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_calculation_engine;
        break;
      }

      // optional .TSP.Reference calculation_engine = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_calculation_engine:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_calculation_engine()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_view_state;
        break;
      }

      // optional .TSP.Reference view_state = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_view_state:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_view_state()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_function_browser_state;
        break;
      }

      // optional .TSP.Reference function_browser_state = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_function_browser_state:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_function_browser_state()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_tables_custom_format_list;
        break;
      }

      // optional .TSP.Reference tables_custom_format_list = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tables_custom_format_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_tables_custom_format_list()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_needs_movie_compatibility_upgrade;
        break;
      }

      // optional bool needs_movie_compatibility_upgrade = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_needs_movie_compatibility_upgrade:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &needs_movie_compatibility_upgrade_)));
          set_has_needs_movie_compatibility_upgrade();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(74)) goto parse_template_identifier;
        break;
      }

      // optional string template_identifier = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_template_identifier:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_template_identifier()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->template_identifier().data(), this->template_identifier().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DocumentArchive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .TSK.DocumentArchive super = 1;
  if (has_super()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->super(), output);
  }

  // repeated .TSWP.TextPresetDisplayItemArchive text_preset_display_items = 2;
  for (int i = 0; i < this->text_preset_display_items_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->text_preset_display_items(i), output);
  }

  // optional string creation_language = 3;
  if (has_creation_language()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->creation_language().data(), this->creation_language().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->creation_language(), output);
  }

  // optional .TSP.Reference calculation_engine = 4;
  if (has_calculation_engine()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->calculation_engine(), output);
  }

  // optional .TSP.Reference view_state = 5;
  if (has_view_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->view_state(), output);
  }

  // optional .TSP.Reference function_browser_state = 6;
  if (has_function_browser_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->function_browser_state(), output);
  }

  // optional .TSP.Reference tables_custom_format_list = 7;
  if (has_tables_custom_format_list()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->tables_custom_format_list(), output);
  }

  // optional bool needs_movie_compatibility_upgrade = 8;
  if (has_needs_movie_compatibility_upgrade()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->needs_movie_compatibility_upgrade(), output);
  }

  // optional string template_identifier = 9;
  if (has_template_identifier()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->template_identifier().data(), this->template_identifier().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      9, this->template_identifier(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DocumentArchive::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .TSK.DocumentArchive super = 1;
  if (has_super()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->super(), target);
  }

  // repeated .TSWP.TextPresetDisplayItemArchive text_preset_display_items = 2;
  for (int i = 0; i < this->text_preset_display_items_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->text_preset_display_items(i), target);
  }

  // optional string creation_language = 3;
  if (has_creation_language()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->creation_language().data(), this->creation_language().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->creation_language(), target);
  }

  // optional .TSP.Reference calculation_engine = 4;
  if (has_calculation_engine()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->calculation_engine(), target);
  }

  // optional .TSP.Reference view_state = 5;
  if (has_view_state()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->view_state(), target);
  }

  // optional .TSP.Reference function_browser_state = 6;
  if (has_function_browser_state()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->function_browser_state(), target);
  }

  // optional .TSP.Reference tables_custom_format_list = 7;
  if (has_tables_custom_format_list()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->tables_custom_format_list(), target);
  }

  // optional bool needs_movie_compatibility_upgrade = 8;
  if (has_needs_movie_compatibility_upgrade()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->needs_movie_compatibility_upgrade(), target);
  }

  // optional string template_identifier = 9;
  if (has_template_identifier()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->template_identifier().data(), this->template_identifier().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->template_identifier(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DocumentArchive::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .TSK.DocumentArchive super = 1;
    if (has_super()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->super());
    }

    // optional string creation_language = 3;
    if (has_creation_language()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->creation_language());
    }

    // optional .TSP.Reference calculation_engine = 4;
    if (has_calculation_engine()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->calculation_engine());
    }

    // optional .TSP.Reference view_state = 5;
    if (has_view_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->view_state());
    }

    // optional .TSP.Reference function_browser_state = 6;
    if (has_function_browser_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->function_browser_state());
    }

    // optional .TSP.Reference tables_custom_format_list = 7;
    if (has_tables_custom_format_list()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->tables_custom_format_list());
    }

    // optional bool needs_movie_compatibility_upgrade = 8;
    if (has_needs_movie_compatibility_upgrade()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional string template_identifier = 9;
    if (has_template_identifier()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->template_identifier());
    }

  }
  // repeated .TSWP.TextPresetDisplayItemArchive text_preset_display_items = 2;
  total_size += 1 * this->text_preset_display_items_size();
  for (int i = 0; i < this->text_preset_display_items_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->text_preset_display_items(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DocumentArchive::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DocumentArchive* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DocumentArchive*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DocumentArchive::MergeFrom(const DocumentArchive& from) {
  GOOGLE_CHECK_NE(&from, this);
  text_preset_display_items_.MergeFrom(from.text_preset_display_items_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_super()) {
      mutable_super()->::TSK::DocumentArchive::MergeFrom(from.super());
    }
    if (from.has_creation_language()) {
      set_creation_language(from.creation_language());
    }
    if (from.has_calculation_engine()) {
      mutable_calculation_engine()->::TSP::Reference::MergeFrom(from.calculation_engine());
    }
    if (from.has_view_state()) {
      mutable_view_state()->::TSP::Reference::MergeFrom(from.view_state());
    }
    if (from.has_function_browser_state()) {
      mutable_function_browser_state()->::TSP::Reference::MergeFrom(from.function_browser_state());
    }
    if (from.has_tables_custom_format_list()) {
      mutable_tables_custom_format_list()->::TSP::Reference::MergeFrom(from.tables_custom_format_list());
    }
    if (from.has_needs_movie_compatibility_upgrade()) {
      set_needs_movie_compatibility_upgrade(from.needs_movie_compatibility_upgrade());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_template_identifier()) {
      set_template_identifier(from.template_identifier());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DocumentArchive::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DocumentArchive::CopyFrom(const DocumentArchive& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DocumentArchive::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_super()) {
    if (!this->super().IsInitialized()) return false;
  }
  for (int i = 0; i < text_preset_display_items_size(); i++) {
    if (!this->text_preset_display_items(i).IsInitialized()) return false;
  }
  if (has_calculation_engine()) {
    if (!this->calculation_engine().IsInitialized()) return false;
  }
  if (has_view_state()) {
    if (!this->view_state().IsInitialized()) return false;
  }
  if (has_function_browser_state()) {
    if (!this->function_browser_state().IsInitialized()) return false;
  }
  if (has_tables_custom_format_list()) {
    if (!this->tables_custom_format_list().IsInitialized()) return false;
  }
  return true;
}

void DocumentArchive::Swap(DocumentArchive* other) {
  if (other != this) {
    std::swap(super_, other->super_);
    text_preset_display_items_.Swap(&other->text_preset_display_items_);
    std::swap(creation_language_, other->creation_language_);
    std::swap(calculation_engine_, other->calculation_engine_);
    std::swap(view_state_, other->view_state_);
    std::swap(function_browser_state_, other->function_browser_state_);
    std::swap(tables_custom_format_list_, other->tables_custom_format_list_);
    std::swap(needs_movie_compatibility_upgrade_, other->needs_movie_compatibility_upgrade_);
    std::swap(template_identifier_, other->template_identifier_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DocumentArchive::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DocumentArchive_descriptor_;
  metadata.reflection = DocumentArchive_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FunctionBrowserStateArchive::kRecentFunctionsFieldNumber;
const int FunctionBrowserStateArchive::kBackFunctionsFieldNumber;
const int FunctionBrowserStateArchive::kForwardFunctionsFieldNumber;
const int FunctionBrowserStateArchive::kCurrentFunctionFieldNumber;
#endif  // !_MSC_VER

FunctionBrowserStateArchive::FunctionBrowserStateArchive()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void FunctionBrowserStateArchive::InitAsDefaultInstance() {
}

FunctionBrowserStateArchive::FunctionBrowserStateArchive(const FunctionBrowserStateArchive& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void FunctionBrowserStateArchive::SharedCtor() {
  _cached_size_ = 0;
  current_function_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FunctionBrowserStateArchive::~FunctionBrowserStateArchive() {
  SharedDtor();
}

void FunctionBrowserStateArchive::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FunctionBrowserStateArchive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FunctionBrowserStateArchive::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FunctionBrowserStateArchive_descriptor_;
}

const FunctionBrowserStateArchive& FunctionBrowserStateArchive::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TSAArchives_2eproto();
  return *default_instance_;
}

FunctionBrowserStateArchive* FunctionBrowserStateArchive::default_instance_ = NULL;

FunctionBrowserStateArchive* FunctionBrowserStateArchive::New() const {
  return new FunctionBrowserStateArchive;
}

void FunctionBrowserStateArchive::Clear() {
  if (_has_bits_[3 / 32] & (0xffu << (3 % 32))) {
    current_function_ = 0u;
  }
  recent_functions_.Clear();
  back_functions_.Clear();
  forward_functions_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool FunctionBrowserStateArchive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 recent_functions = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_recent_functions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 8, input, this->mutable_recent_functions())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_recent_functions())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_recent_functions;
        if (input->ExpectTag(16)) goto parse_back_functions;
        break;
      }

      // repeated uint32 back_functions = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_back_functions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 16, input, this->mutable_back_functions())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_back_functions())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_back_functions;
        if (input->ExpectTag(24)) goto parse_forward_functions;
        break;
      }

      // repeated uint32 forward_functions = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_forward_functions:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 24, input, this->mutable_forward_functions())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_forward_functions())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_forward_functions;
        if (input->ExpectTag(32)) goto parse_current_function;
        break;
      }

      // optional uint32 current_function = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_current_function:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &current_function_)));
          set_has_current_function();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FunctionBrowserStateArchive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated uint32 recent_functions = 1;
  for (int i = 0; i < this->recent_functions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      1, this->recent_functions(i), output);
  }

  // repeated uint32 back_functions = 2;
  for (int i = 0; i < this->back_functions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      2, this->back_functions(i), output);
  }

  // repeated uint32 forward_functions = 3;
  for (int i = 0; i < this->forward_functions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      3, this->forward_functions(i), output);
  }

  // optional uint32 current_function = 4;
  if (has_current_function()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->current_function(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* FunctionBrowserStateArchive::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated uint32 recent_functions = 1;
  for (int i = 0; i < this->recent_functions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(1, this->recent_functions(i), target);
  }

  // repeated uint32 back_functions = 2;
  for (int i = 0; i < this->back_functions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(2, this->back_functions(i), target);
  }

  // repeated uint32 forward_functions = 3;
  for (int i = 0; i < this->forward_functions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(3, this->forward_functions(i), target);
  }

  // optional uint32 current_function = 4;
  if (has_current_function()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->current_function(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int FunctionBrowserStateArchive::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[3 / 32] & (0xffu << (3 % 32))) {
    // optional uint32 current_function = 4;
    if (has_current_function()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->current_function());
    }

  }
  // repeated uint32 recent_functions = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->recent_functions_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->recent_functions(i));
    }
    total_size += 1 * this->recent_functions_size() + data_size;
  }

  // repeated uint32 back_functions = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->back_functions_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->back_functions(i));
    }
    total_size += 1 * this->back_functions_size() + data_size;
  }

  // repeated uint32 forward_functions = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->forward_functions_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->forward_functions(i));
    }
    total_size += 1 * this->forward_functions_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FunctionBrowserStateArchive::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const FunctionBrowserStateArchive* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FunctionBrowserStateArchive*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FunctionBrowserStateArchive::MergeFrom(const FunctionBrowserStateArchive& from) {
  GOOGLE_CHECK_NE(&from, this);
  recent_functions_.MergeFrom(from.recent_functions_);
  back_functions_.MergeFrom(from.back_functions_);
  forward_functions_.MergeFrom(from.forward_functions_);
  if (from._has_bits_[3 / 32] & (0xffu << (3 % 32))) {
    if (from.has_current_function()) {
      set_current_function(from.current_function());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void FunctionBrowserStateArchive::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FunctionBrowserStateArchive::CopyFrom(const FunctionBrowserStateArchive& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FunctionBrowserStateArchive::IsInitialized() const {

  return true;
}

void FunctionBrowserStateArchive::Swap(FunctionBrowserStateArchive* other) {
  if (other != this) {
    recent_functions_.Swap(&other->recent_functions_);
    back_functions_.Swap(&other->back_functions_);
    forward_functions_.Swap(&other->forward_functions_);
    std::swap(current_function_, other->current_function_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata FunctionBrowserStateArchive::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FunctionBrowserStateArchive_descriptor_;
  metadata.reflection = FunctionBrowserStateArchive_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TestDocumentArchive::kSuperFieldNumber;
const int TestDocumentArchive::kValueFieldNumber;
#endif  // !_MSC_VER

TestDocumentArchive::TestDocumentArchive()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TestDocumentArchive::InitAsDefaultInstance() {
  super_ = const_cast< ::TSA::DocumentArchive*>(&::TSA::DocumentArchive::default_instance());
}

TestDocumentArchive::TestDocumentArchive(const TestDocumentArchive& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TestDocumentArchive::SharedCtor() {
  _cached_size_ = 0;
  super_ = NULL;
  value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TestDocumentArchive::~TestDocumentArchive() {
  SharedDtor();
}

void TestDocumentArchive::SharedDtor() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (this != default_instance_) {
    delete super_;
  }
}

void TestDocumentArchive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TestDocumentArchive::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TestDocumentArchive_descriptor_;
}

const TestDocumentArchive& TestDocumentArchive::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TSAArchives_2eproto();
  return *default_instance_;
}

TestDocumentArchive* TestDocumentArchive::default_instance_ = NULL;

TestDocumentArchive* TestDocumentArchive::New() const {
  return new TestDocumentArchive;
}

void TestDocumentArchive::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_super()) {
      if (super_ != NULL) super_->::TSA::DocumentArchive::Clear();
    }
    if (has_value()) {
      if (value_ != &::google::protobuf::internal::kEmptyString) {
        value_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TestDocumentArchive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .TSA.DocumentArchive super = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_super()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_value;
        break;
      }

      // optional string value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_value:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TestDocumentArchive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .TSA.DocumentArchive super = 1;
  if (has_super()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->super(), output);
  }

  // optional string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->value(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TestDocumentArchive::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .TSA.DocumentArchive super = 1;
  if (has_super()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->super(), target);
  }

  // optional string value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TestDocumentArchive::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .TSA.DocumentArchive super = 1;
    if (has_super()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->super());
    }

    // optional string value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->value());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TestDocumentArchive::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TestDocumentArchive* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TestDocumentArchive*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TestDocumentArchive::MergeFrom(const TestDocumentArchive& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_super()) {
      mutable_super()->::TSA::DocumentArchive::MergeFrom(from.super());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TestDocumentArchive::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TestDocumentArchive::CopyFrom(const TestDocumentArchive& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestDocumentArchive::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_super()) {
    if (!this->super().IsInitialized()) return false;
  }
  return true;
}

void TestDocumentArchive::Swap(TestDocumentArchive* other) {
  if (other != this) {
    std::swap(super_, other->super_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TestDocumentArchive::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TestDocumentArchive_descriptor_;
  metadata.reflection = TestDocumentArchive_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PropagatePresetCommandArchive::kSuperFieldNumber;
#endif  // !_MSC_VER

PropagatePresetCommandArchive::PropagatePresetCommandArchive()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PropagatePresetCommandArchive::InitAsDefaultInstance() {
  super_ = const_cast< ::TSK::CommandArchive*>(&::TSK::CommandArchive::default_instance());
}

PropagatePresetCommandArchive::PropagatePresetCommandArchive(const PropagatePresetCommandArchive& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PropagatePresetCommandArchive::SharedCtor() {
  _cached_size_ = 0;
  super_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PropagatePresetCommandArchive::~PropagatePresetCommandArchive() {
  SharedDtor();
}

void PropagatePresetCommandArchive::SharedDtor() {
  if (this != default_instance_) {
    delete super_;
  }
}

void PropagatePresetCommandArchive::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PropagatePresetCommandArchive::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PropagatePresetCommandArchive_descriptor_;
}

const PropagatePresetCommandArchive& PropagatePresetCommandArchive::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TSAArchives_2eproto();
  return *default_instance_;
}

PropagatePresetCommandArchive* PropagatePresetCommandArchive::default_instance_ = NULL;

PropagatePresetCommandArchive* PropagatePresetCommandArchive::New() const {
  return new PropagatePresetCommandArchive;
}

void PropagatePresetCommandArchive::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_super()) {
      if (super_ != NULL) super_->::TSK::CommandArchive::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PropagatePresetCommandArchive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .TSK.CommandArchive super = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_super()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PropagatePresetCommandArchive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .TSK.CommandArchive super = 1;
  if (has_super()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->super(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PropagatePresetCommandArchive::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .TSK.CommandArchive super = 1;
  if (has_super()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->super(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PropagatePresetCommandArchive::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .TSK.CommandArchive super = 1;
    if (has_super()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->super());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PropagatePresetCommandArchive::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PropagatePresetCommandArchive* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PropagatePresetCommandArchive*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PropagatePresetCommandArchive::MergeFrom(const PropagatePresetCommandArchive& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_super()) {
      mutable_super()->::TSK::CommandArchive::MergeFrom(from.super());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PropagatePresetCommandArchive::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PropagatePresetCommandArchive::CopyFrom(const PropagatePresetCommandArchive& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PropagatePresetCommandArchive::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_super()) {
    if (!this->super().IsInitialized()) return false;
  }
  return true;
}

void PropagatePresetCommandArchive::Swap(PropagatePresetCommandArchive* other) {
  if (other != this) {
    std::swap(super_, other->super_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PropagatePresetCommandArchive::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PropagatePresetCommandArchive_descriptor_;
  metadata.reflection = PropagatePresetCommandArchive_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace TSA

// @@protoc_insertion_point(global_scope)
